### ISSUE TITLE
Draw basic concept of calculation process

### ISSUE THREAD

**Issue by philippabele** [philippabele/ball-bearings-with-quarkus#27]
- refactor your demo workflow with a real process
- calculate the lifetime for ball bearings in O arrangement
- focus on the high level visualization
- detail functions like catalog calculation according specific product catalogs will be detailed later

**Comment by TheMaxens** [comment]
Is it possible that there are incorrect values in the data provided in the Excel? 
For Example, the value for "a" should be the same as "y2" (10), but it is 0.  

Another question: 
The variables "FrB" and "FaB" in the Visual Basic-script refer to the bearing B, right?

**Comment by philippabele** [comment]
Yes, you're right.

_B refers to bearing B

**Comment by TheMaxens** [comment]
How can I get rid of this error?
![image](https://user-images.githubusercontent.com/77580919/203543280-2dfe6af5-9776-44dc-bafd-ff2007f84ad1.png)

I have already tried `=@'ball-bearings-with-quarkus-r05.xlsm'!Lh10_C0.Lh10_OAnordnung(F4;F5;F6;F10;F11;F8;F9;F13;F14;F15;F16;G13;G14;G15;G16;100;0)` but the error still occurs.

**Comment by philippabele** [comment]
There is an Issue when switching from German to US Settings in Excel.

For example:

- German Version of a Formula `=myCalc(F1;F2)`
- US Version of a Formula `=myCalc(F1,F2)`

Please notice, that you have to exchange ";" with ","

**Comment by philippabele** [comment]
@TheMaxens 

If you take a Cell Formula from Sheet 1 like `=myCalc(F1,F2)` and move it to another sheet Sheet2. You have to tell Excel explicitly where to find the cells, like `=myCalc(Sheet1!F1,Sheet1!F2)`
