### ISSUE TITLE
Init data model of ball bearing

### ISSUE THREAD

**Issue by philippabele** [philippabele/ball-bearings-with-quarkus#31]
Init a data model for ball bearings:

- try to find a place for all parameters of a ball bearing

After creating the data model replace your fruits endpoint with the ball bearings data model to:
- get
- post
- update
- delete
bearings.

Do not add a external database. this will be done in a later step of this project.

**Comment by TheMaxens** [comment]
I tried to exchange ";" with "," and added "Sheet1!" in the Excel but the error still occurs. 

Do you have another advice?
 
If not, it would also be enough for me if you send me the corresponding results of the functions. 

Another question: 
![image](https://user-images.githubusercontent.com/77580919/203781025-eb98095e-5da4-4175-b284-d93b1a6d40fd.png)
What is meant by "a1 > aA > xB1" or "a2 > aB > xB2"?

**Comment by philippabele** [comment]
I think we should do a short web meeting to fix your issue. Today at 9 pm?

**Comment by TheMaxens** [comment]
9 pm works for me.

**Comment by philippabele** [comment]
I will send you a link via email later, just before the meeting to join.
