### ISSUE TITLE
Write a Test for your Bearing Endpoint

### ISSUE THREAD

**Issue by philippabele** [philippabele/ball-bearings-with-quarkus#35]
In your Hands On Book about Cloud Native with Quarkus, there is chapter about testing your application with rest-assured.

Write a test, to test your endpoint.

https://github.com/rest-assured/rest-assured/wiki/usage#example-1---json

By the way, tests are a great way to show how to use your endpoint. So keep in mind, that well written tests will be reused in your documentation to explain how to work with your project.

**Comment by TheMaxens** [comment]
Should I test for the whole JSON or just for the corresponding values in the JSON?

**Comment by philippabele** [comment]
Schema Validation looks interessting, I would give it a try.

What do you mean with corresponding values in the JSON?

**Comment by TheMaxens** [comment]
As in this example: https://github.com/rest-assured/rest-assured/wiki/usage#example-1---json

It is not looking for the whole JSON, just for the values `lotto.lottoId` and `lotto.winners.winnerId`.

**Comment by philippabele** [comment]
Okay, I see your point. Let's switch the focus to just for values as you suggested.

We will fix the topic schema validation on another way.

Sorry for the little mess :-)

**Comment by TheMaxens** [comment]
The problem with testing the whole JSON is that the IDs are generated and therefore difficult to test. 
I think it makes sense to test all values apart from the IDs.

**Comment by philippabele** [comment]
It just depends on the task you perform before.

If you create a new bearing, you will receive an ID.

This received ID can be used for testing a get route.

These are common problems, if you write tests. Sometimes you need to perform some other tasks, to test the actual route.
