### ISSUE TITLE
Create POJOs for the Domain Model - Class Bearing

### ISSUE THREAD

**Issue by philippabele** [philippabele/ball-bearings-with-quarkus#40]
Solve this issue after #39 

https://github.com/philippabele/ball-bearings-with-quarkus/blob/ba359b20503cf22d5b05d8829437bbd859564406/src/main/java/org/dhbw/mosbach/ai/Bearing.java#L17

Copy your classes:
- Bearing
- Load (not inlcuded in this issues anymore)
- OArrangement (not inlcuded in this issues anymore)

into the folder /domain/model

Transform them into POJOs like the following example

https://github.com/philippabele/hexagonale-architecture/blob/7aff2ff2c2f2c308c4b424464b4957a457449021/src/main/java/com/hexaclean/arc/demo/app/vehicle/domain/model/Vehicle.java

https://github.com/philippabele/hexagonale-architecture/blob/7aff2ff2c2f2c308c4b424464b4957a457449021/src/main/java/com/hexaclean/arc/demo/app/vehicle/domain/model/VehicleModel.java

**Comment by philippabele** [comment]
Please create for each issue a single branch and a single PR

**Comment by TheMaxens** [comment]
I have not yet understood how to transform the classes. 
Can you help me further?

**Comment by philippabele** [comment]
Okay, let us split the task into smaller units.

I will rename this issue in order to focus on the bearing class. Afterwards we will take care about the other entities.

**Comment by TheMaxens** [comment]
Is there any connection between the class `Vehicle` and `VehicleModel` in your example? I wasn't able to figure it out,

**Comment by TheMaxens** [comment]
Is there any connection between the classes `Vehicle` and `VehicleModel` in your example? I wasn't able to figure it out?

**Comment by philippabele** [comment]
You are right. The `VehicleModel` example is unnecessary.

So just use the `Vehicle` class.

**Comment by philippabele** [comment]
Did you know, that you can generate UML classes from Java code ?

https://www.visual-paradigm.com/support/documents/vpuserguide/276/381/7530_generateorup.html

With this feature you are able to analyse the source of foreign projects.

**Comment by TheMaxens** [comment]
Do you know which of the branches is the correct or recent one? The structure is changing from branch to branch.

**Comment by philippabele** [comment]
You can focus on the branches with "solution" in the name.

With ascending numbering, the branches include more and more features.

So, take a look at solution 1, then solution 2, you will discover a pattern and the methodology.

**Comment by TheMaxens** [comment]
Unfortunately, I don't really understand what I should do or what the result should look like.

**Comment by philippabele** [comment]
Should we arrange a call? I would suggest some time slots if you are interested.

**Comment by TheMaxens** [comment]
Yes, that makes sense.
